import OpenAI from 'openai';
import type { AppearanceDefinition } from '@picture-book/shared';
import type { StoryResult } from './story-engine.js';
import { createOpenAIClient } from '../lib/openai.js';

export interface GenerateAppearancesInput {
  story: StoryResult;
  autoGeneratedRoles: { role: string; label: string }[];
}

export interface GenerateAppearancesResult {
  appearances: Map<string, AppearanceDefinition>;
}

function buildAppearancePrompt(input: GenerateAppearancesInput): string {
  const storyText = input.story.pages
    .map((p) => `Page ${p.pageNumber}: "${p.text}"`)
    .join('\n');

  const characterList = input.autoGeneratedRoles
    .map((r) => `- [${r.role}] ${r.label} (${r.role} role)`)
    .join('\n');

  return `You are a character designer for a children's picture book.
Based on the story text below, generate detailed appearance definitions for the following auto-generated characters.

STORY:
${storyText}

CHARACTERS TO DEFINE:
${characterList}

For each character, provide:
- hairStyle: detailed hair description
- hairColor: specific color
- clothing: full outfit description (top, bottom, shoes)
- bodyType: build and height relative to age
- ageGroup: approximate age range
- distinguishingFeatures: unique visual features

IMPORTANT:
- Descriptions must be in English
- Must be consistent with any character descriptions in the story text
- Must be specific enough for an illustrator to draw the same character consistently
- Use warm, friendly, picture-book-appropriate descriptions

Output as JSON:
{
  "appearances": [
    {
      "role": "friend",
      "name": "Tanaka-kun",
      "hairStyle": "...",
      "hairColor": "...",
      "clothing": "...",
      "bodyType": "...",
      "ageGroup": "...",
      "distinguishingFeatures": "..."
    }
  ]
}`;
}

function parseAppearancesResponse(
  content: string,
  roles: { role: string; label: string }[]
): Map<string, AppearanceDefinition> {
  const result = new Map<string, AppearanceDefinition>();
  const parsed = JSON.parse(content);

  const appearances: unknown[] = Array.isArray(parsed.appearances)
    ? parsed.appearances
    : [];

  for (const role of roles) {
    const match = appearances.find(
      (a: unknown) =>
        typeof a === 'object' && a !== null && (a as Record<string, unknown>).role === role.role
    ) as Record<string, unknown> | undefined;

    if (!match) continue;

    const def: AppearanceDefinition = {
      role: role.role,
      name: typeof match.name === 'string' && match.name ? match.name : role.label,
      hairStyle: typeof match.hairStyle === 'string' && match.hairStyle ? match.hairStyle : '',
      hairColor: typeof match.hairColor === 'string' && match.hairColor ? match.hairColor : '',
      clothing: typeof match.clothing === 'string' && match.clothing ? match.clothing : '',
      bodyType: typeof match.bodyType === 'string' && match.bodyType ? match.bodyType : '',
      ageGroup: typeof match.ageGroup === 'string' && match.ageGroup ? match.ageGroup : '',
      distinguishingFeatures:
        typeof match.distinguishingFeatures === 'string' && match.distinguishingFeatures
          ? match.distinguishingFeatures
          : '',
    };

    result.set(role.role, def);
  }

  return result;
}

/**
 * auto_generated ロールの外見定義を GPT-4o で生成する。
 * ストーリーテキスト内のキャラクター描写と矛盾しない定義を生成する。
 * エラー時は空の Map を返す（Graceful Degradation）。
 */
export async function generateAppearances(
  input: GenerateAppearancesInput,
  openaiClient?: OpenAI
): Promise<GenerateAppearancesResult> {
  if (input.autoGeneratedRoles.length === 0) {
    return { appearances: new Map() };
  }

  try {
    const client = openaiClient ?? createOpenAIClient();
    const prompt = buildAppearancePrompt(input);

    console.log(
      `[sub-character-generator] Generating appearances for ${input.autoGeneratedRoles.length} role(s)...`
    );

    const response = await client.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content:
            'You are a character designer for a children\'s picture book. Generate detailed, consistent appearance definitions in English. Always respond with valid JSON.',
        },
        { role: 'user', content: prompt },
      ],
      temperature: 0.7,
      response_format: { type: 'json_object' },
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      console.error('[sub-character-generator] Empty response from OpenAI API');
      return { appearances: new Map() };
    }

    const appearances = parseAppearancesResponse(content, input.autoGeneratedRoles);
    console.log(
      `[sub-character-generator] Generated ${appearances.size} appearance definition(s)`
    );
    return { appearances };
  } catch (error) {
    console.error(
      '[sub-character-generator] Failed to generate appearances:',
      error instanceof Error ? error.message : String(error)
    );
    return { appearances: new Map() };
  }
}

// Exported for testing
export { buildAppearancePrompt, parseAppearancesResponse };
